'use strict';
var mongoose = require('mongoose');
var newId = mongoose.Types.ObjectId;
// default data that can be used to get started from an empty db


exports.actions = [
    {
        "category": "refrigrator",
        "name": "Keep the fridge doors closed as much as possible.",
        "description": "Refrigerators often account for as much as 15% of your home's total energy usage. Help your refrigerator and freezer operate efficiently and economically by keeping the fridge doors closed as much as possible so the cold air doesn't escape. Moreover, leaving the frige door open for a longer period of time while you take out the items you need is more efficient than opening and closing it several times.",
        "nameSe": "Håll dörrarna till kyl och frys stängda så mycket som möjligt.",
        "descriptionSe": "Hjälp din kyl och frys and vara mer energieffektiv genom att hålla dörrarna stängda så mycket som möjligt så att inte kylan försvinner ut i onödan. Men om du ska plocka ut eller in många saker är det bättre att hålla dörrarna öppna under hela tiden istället för att öppna och stänga flera gånger.",
        "nameIt": "Tieni la porta del frigo chiusa, per quando possibile.",
        "descriptionIt": "Fino al 15% del consumo energetico di una casa è legato all'uso di frigoriferi e congelatori. Per fare in modo che frigo e freezer lavorino in modo efficiente, gli sportelli devono rimanere quanto più possibili chiusi. Considera però che, se ti servono varie cose, aprire una volta sola il frigo per un periodo di tempo più lungo è più efficiente che continuare ad aprirlo e chiuderlo per prendere quel che ti serve di volta in volta.",
        "type": "common",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "refrigrator",
        "name": "Fill up your fridge but don't cram it too full.",
        "description": "Keep your refrigerator and freezer full is energy efficient, because the mass of cold items inside will help your refrigerator recover each time the door is opened. Don't cram it too full, however, that cool air can't circulate properly around your food.",
        "nameSe": "Fyll kyl och frys men undvik att det blir fullproppat.",
        "descriptionSe": "Att hålla kyl och frys relativt fulla är energieffektivt för de kalla varorna i kylen/frysen minskar förlusten av kyla varje gång dörren öppnas. Men se upp så att det inte blir för fullproppat  för då kan inte den kalla luften cirkulera ordentligt.",
        "nameIt": "È bene che il frigo sia pieno, ma non stracolmo.",
        "descriptionIt": "Il fatto che ci siano degli oggetti freddi nel frigo/congelatore, aiuta a ristabilire più velocemente la temperatura quando si apre e si chiude lo sportello. Considera però che il cibo non deve essere ammassato, per permettere all'aria di circolare. Evita quindi di riempire frigo e freezer a dismisura.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "refrigrator",
        "name": "Allow food to cool down first before placing it in the refrigerator.",
        "description": "It wiil be energy intensive to cool down warm food into frige tempreture.",
        "nameSe": "Låt varm mat svalna innan du ställer in den i kylen eller frysen.",
        "descriptionSe": "Det tar mycket energi att kyla varm mat till kyl- eller frystemperatur.",
        "nameIt": "Fai raffreddare il cibo prima di metterlo in frigo.",
        "descriptionIt": "Mettere del cibo caldo nel frigorifero comporta un dispendio energetico elevato. Aspetta che il cibo sia a temperatura ambiente prima di riporlo nel frigo/freezer",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "refrigrator",
        "name": "Set your frige in the right temparature. Suitable frige temperature: 4-5°C, freezer: -18°C.",
        "description": "A refrigerator works best if you set the temperature at 4-5°C and a freezer works best at a temperature of -18°C. Setting them at a lower temperature is therefore pointless and wastes energy. For every degree increase, there is approximate 5% decrease of energy.",
        "nameSe": "Ha rätt temperatur på kyl och frys: 4-5 °C för kyl och -18°C för frys.",
        "descriptionSe": "Kylen fungerar bäst om temperaturen är 4-5°C och frysen fungerar bäst vid -18°C. Att ha längre temperaturer har inga fördelar utan är därför bara slöseri med energi. För varje grad lägre drar kylen/frysen ungefär 5% mer energi.",
        "nameIt": "Regola il tuo frigorifero sulla giusta temperatura: 4-5° C per il frigorifero, -18° C per il congelatore.",
        "descriptionIt": "La temperatura ideale a cui regolare il frigorifero è di 4-5°C e quella a cui regolare il congelatore -18°C. Tenerli ad una temperatura inferiore è inutile e per ogni grado in meno si consuma all'incirca il 5% in più.",
        "type": "onetime",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "refrigrator",
        "name": "Defrost your freezer regularly.",
        "description": "Defrost your freezer regularly, e.g., every two months or when ice starts to form.",
        "nameSe": "Frosta av frysen regelbundet.",
        "descriptionSe": "Frosta av frysen regelbundet, t.ex. varannan månad eller när det börjar bildas frost i frysen.",
        "nameIt": "Sbrina il frigo regolarmente.",
        "descriptionIt": "Sbrina il frigo non appena il ghiaccio inizia a formarsi.",
        "type": "regular",
        "impact": 3,
        "effort": 3
    },
    {
        "category": "refrigrator",
        "name": "Use energy efficient fridge and freezer.",
        "description": "When the fridge or freezer needs to be replaced, make sure the new one has a good energy label, e.g., A+, A++, A+++",
        "nameSe": "Använd energieffektiva kylskåp och frysar.",
        "descriptionSe": "När kyl och frys behöver ersättas, se till att de har A-klassad energimärkning, d.v.s. A+, A++ eller A+++.",
        "type": "onetime",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "refrigrator",
        "name": "Unplug unused fridge.",
        "description": "Switch off the refrigerator and freezer if you are going away for a long time. Leave the doors open slightly to prevent the formation of mould. In case you have a spare refrigerator in the garage, unplug it if you don't truly need it - this seemingly convenient way to keep extra drinks cold adds 10-25% to your electric bill.",
        "nameSe": "Koppla ur kyl eller frys när den inte ska användas på länge.",
        "descriptionSe": "Om du ska resa bort eller har en oanvänd kyl/frys stående, se till att koppla ur den. Lämna dörrarna på glänt för att mögel bildas på insidan.",
        "nameIt": "Stacca il frigo se non lo usi.",
        "descriptionIt": "Quando lasci casa per un lungo periodo di tempo, accertati di aver staccato il frigorifero ed eventualmente anche il congelatore. Lascia gli sportelli aperti per evitare la formazione di muffe. Se in casa ci sono più frigoriferi/congelatori, considera di spegnerne uno, nei periodi in cui non ce ne sia effettivo bisogno.",
        "type": "irregular",
        "impact": 4,
        "effort": 3
    },
    {
        "category": "refrigrator",
        "name": "Clean or vacuum dust from the back of the fridge or freezer.",
        "description": "Accumulated dust increases energy consumption. Also make sure there is an air gap on the back of the firdge.",
        "nameSe": "Dammsug eller torka bakom kyl och frys.",
        "descriptionSe": "Om det samlas damm bakom kyl och frys ökar energianvändningen. Se också till att det finns en luftspalt mellan kylen/ frysen och väggen.",
        "nameIt": "Spolvera il retro di frigorifero e congelatore.",
        "descriptionIt": "La serpentina sul retro di frigoriferi/congelatori ha bisogno di un buon passaggio d'aria per funzionare al meglio: accertati che non siano troppo attaccati al muro e che la serpentina non sia impolverata.",
        "type": "regular",
        "impact": 3,
        "effort": 3
    },
    {
        "category": "refrigrator",
        "name": "Thaw food in the refrigerator.",
        "description": "Thawing in the refrigerator uses much less energy than in the microwave. You can reuse the released cold in the refrigerator.",
        "nameSe": "Tina mat i kylen.",
        "descriptionSe": "Att tina mat i kylen kräver mindre energi än att tina i micron och kylan kan återanvändas, vilket minskar kylens energianvändning.",
        "nameIt": "Scongela il cibo nel frigorifero.",
        "descriptionIt": "Se hai tempo, scongela quel che ti serve mettendolo in frigo e avrai un doppio beneficio: il cibo congelato contribuirà a raffreddare il cibo e risparmierai l'elettricità del microonde o il gas utilizzati per scongelare.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "general",
        "name": "Do you consistently turn off appliances and lights when they are not in use?",
        "description": "Don't forget to turn off appliances, lights and equipment when they are not in use. Save 2%.\n",
        "nameSe": "Stäng av apparater och släck lampor när de inte används.",
        "descriptionSe": "Glöm inte att stänga av apparater och utrustning, och släcka lampor, när de inte används.",
        "nameIt": "Spegni regolarmente elettrodomestici e luci, quando non ti servono?",
        "descriptionIt": "Non dimenticarti di spegnere elettrodomestici e luci, quando non ti servono più.",
        "type": "common",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "general",
        "name": "Choose appliances with low energy consumption if you can.",
        "description": "Old appliances often consume significantly more energy than modern ones. If you need to buy appliances, always choose those with low energy consumption. They are labelled with A+, A++, A+++.",
        "nameSe": "Välj om möjligt apparater med låg energianvändning.",
        "descriptionSe": "Gamla apparater kräver ofta mycket mer energi än nyare apparater. Om du behöver köpa nytt, välj apparater med A-klassad energimärkning, d.v.s. A+, A++ eller A+++.",
        "nameIt": "Se puoi, scegli elettrodomestici a basso consumo.",
        "descriptionIt": "I vecchi elettrodomestici hanno consumi significativamente superiori rispetto a quelli moderni. Se ti trovi a sostituirli, scegli sempre quelli ad alta efficienza energetica (da A+ in su)",
        "type": "irregular",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "general",
        "name": "Turn off standby power of TV, stereo, computer, etc.",
        "description": "Unplug \"leaking energy\" in electronics: many new TVs, chargers, computer peripherals and other electronics use electricity even when they are switched \"off.\" These \"standby losses\" can add up to more than 50 watts in a typical home that is consumed all the time. If possible, unplug electronic devices and chargers that have a block-shaped transformer on the plug when they are not in use. For computer scanners, printers and other devices that are plugged into a power strip, simply switch off the power strip after shutting down your computer.",
        "nameSe": "Koppla ur TV, stereo, dator och annan hemelektronik som står på standby.",
        "descriptionSe": "Mycket hemelektronik har ett stanbylägen som drar energi även när apparaten är avstängd. Om möjligt, koppla ur apparater helt t.ex. genom att dra ur sladden eller koppla dem till ett grenuttag med strömbrytare.",
        "nameIt": "Scopri quali apparecchi consumano anche da spenti.",
        "descriptionIt": "Molti apparecchi moderni continuano a consumare una piccola quantità di energia anche da spenti. Gli apparecchi a cui prestare attenzione sono TV, caricabatterie, stampanti e in generale tutti gli oggetti che necessitano di un piccolo trasformatore. In una casa tipo, tenere questi apparecchi attaccati alla corrente può far consumare oltre i 50 watt in più quindi andrebbero staccati dalla corrente quando sono spenti. Per facilitare l'operazione è possibile collegarli a un'unica ciabatta e staccare/spegnere solo quella.",
        "type": "common",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "computer",
        "name": "Put your computer and monitor to sleep.",
        "description": "On computers using Windows, open your power management software and set it so your computer goes to sleep if you're away from your machine for 5 to 15 minutes. Those who use Macintosh computers look for the setting in your Control Panels called \"Energy Saver\".",
        "nameSe": "Aktivera viloläge på datorer och skärmar.",
        "descriptionSe": "Ändra inställningarna på din dator så att den automatiskt går i viloläge om du inte använder den på en stund, t.ex. 5-15 minuter.",
        "nameIt": "Programma lo standby automatico del computer.",
        "descriptionIt": "Cerca sul tuo computer le opzioni di risparmio energetico nel pannello impostazioni. In questa sezione puoi stabilire un certo numero di minuti entro cui, se non stai usando il computer, lui automaticamente entrerà in modalità “ibernazione”. La modalità “ibernazione” non spegne il computer, non chiude i file e le finestre aperte e contemporaneamente permette di abbatterne i consumi.",
        "type": "onetime",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "computer",
        "name": "Turn off your computer when it is not in use.",
        "description": "Sleeping computers leak energy. When you're done using your computer, turn it off. Do not leave it in sleep mode overnight as it is still drawing a small amount of power.",
        "nameSe": "Stäng av datorn när du inte använder den.",
        "descriptionSe": "Viloläget på datorer använder fortfarande energi så när stäng av datorn helt när du inte ska använda den på ett tag.",
        "nameIt": "Spegni il computer, se non lo stai usando.",
        "descriptionIt": "I computer in modalità “ibernazione” consumano meno energia dei computer accesi ma ne consumano comunque: non usare la modalità “ibernazione” al posto di spegnere il computer. Considera anche che lasciare costantemente il computer in modalità sleep ne rallenta le prestazioni",
        "type": "routine",
        "impact": 1,
        "effort": 1
    },
    {
        "category": "lights",
        "name": "Replace standard bulbs with energy saving bulbs.",
        "description": "Lighting can account for as much as 25% of a home's electrical use. You can increase the everyday lighting efficiency of your house - without sacrificing its lighting quality - by simply replacing standard bulbs with energy saving bulbs. Lighting efficiency: normal bulds 5%, CFL 45%, LED 90%.",
        "nameSe": "Ersätt vanliga glödlampor med mer energieffektiva alternativ.",
        "descriptionSe": "Belysning kan utgöra så mycket som 25% av ett hushålls totala elanvändning. Du kan öka energieffektiviteten på din belysning, utan att försämra kvalitén, genom att ersätta glödlampor med LED-lampor, halogenlampor eller lågenergilampor. Normala glödlampor har bara en effektivitet på 5% medan LED-lampor har en effektivitet på 90% (d.v.s. 90% av energi blir till ljus).",
        "nameIt": "Sostituisci le lampadine con modelli a basso consumo.",
        "descriptionIt": "Fino al 25% dei consumi domestici di elettricità sono legati all'illuminazione. Puoi migliorare l'efficienza dell'illuminazione semplicemente sostituendo le lampadine: cercare percentuali più chiare",
        "type": "irregular",
        "impact": 3,
        "effort": 3
    },
    {
        "category": "laundry",
        "name": "Do not wash your cloth with too hot water.",
        "description": "Conserve energy by using the cold water setting on your clothes washer when you can. If you use hot water at home to wash your clothes, heating the water is the single largest expense of running a load of laundry. Using cold water reduces your washer's energy use by 75%. 40 degrees is sufficient for a moderately soiled laundry.",
        "nameSe": "Tvätta inte kläder i onödigt höga temperaturer.",
        "descriptionSe": "Minska din energianvändning genom att tvätta i låga temperaturer, 40°C är ofta tillräckligt för kläder som inte är jättesmutsiga.",
        "nameIt": "Non usare acqua troppo calda per lavare i vestiti.",
        "descriptionIt": "Lavare i vestiti alle basse temperature consente di risparmiare fino al 75% dell'energia impiegata dal ciclo di lavaggio. Per la maggior parte dei carichi, 30° o 40° sono temperature sufficienti. (Ricorda: se lavi i vestiti a temperature più basse “invecchieranno” più lentamente)",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "laundry",
        "name": "Do you pre-wash your cloth?",
        "description": "Pre-wash your cloth is not always needed. Use the energy-saving program and skip the pre-wash if possible.",
        "nameSe": "Undivik att förtvätta kläder.",
        "descriptionSe": "Att inkludera förtvätt i tvättprogrammet är ofta onödigt. Anväd energisparprogram om det finns och undvik förtvätt om det går.",
        "nameIt": "Utilizzi spesso la funzione di prelavaggio della lavatrice?",
        "descriptionIt": "Il programma di prelavaggio è utile solo in caso di biancheria veramente molto sporca. Usalo solo quando è utile e, se presenti, scegli i programmi di lavaggio a risparmio energetico.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "laundry",
        "name": "Conserve energy by running the clothes washer and dryer with full loads.",
        "description": "Fill the machine. Today, there are washing machines that weigh the laundry and regulate both water and energy consumption by weight, but it is still more energy efficient to wash with a full machine.",
        "nameSe": "Minska energianvändningen genom att endast tvätta med fulla tvättmaskiner och torktumlare.",
        "descriptionSe": "Fyll maskinerna. Det finns även tvättmaskiner som väger tvätten och anpassar både vatten- och energianvändningen efter det, men det är fortfarande mer effektivt att fylla maskinerna.",
        "nameIt": "Cerca di usare lavatrice e lavastoviglie solo a pieno carico.",
        "descriptionIt": "Cerca di utilizzare la lavatrice solo a pieno carico. Anche se hai una lavatrice moderna che pesa la biancheria e riduce l'acqua di conseguenza, non usare i programmi a mezzo carico è sempre l'opzione più efficiente.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "laundry",
        "name": "Spin dry your cloth thoroughly if possible. Line dry, air dry clothes whenever you can.",
        "description": "Use at least 1000 rpm, if the wash will be tumble dried. Otherwise, the dryer will consume too much energy. Line dry, air dry clothes whenever you can. In the laundry, the drying of clothes that are the most energy consuming, it can go up to three times as much energy to dry clothes than washing. When you need to use the dryer, run full loads, use the moisture-sensing setting (if you have one), and clean the clothes dryer lint trap after each use.",
        "nameSe": "Centrifugera kläderna i tvättmaskinen och låt kläderna hängtorka.",
        "descriptionSe": "Använd minst 1000 varv/minut om kläderna ska torktumlas, för att inte torktumlaren ska dra onödigt mycket energi. Hängtorka kläder istället för att torktumla eller torka i torkskåp/-rum när det är möjligt. Torkning av kläder är ofta den del av tvättningen som drar mest energi, det dra ta upp till tre gånger mer energi än själva tvättningen. När du behäver använda torktumlare, se till att fylla maskinen och glöm inte att ta bort luddet efteråt - det påverkar också energianvändningen.",
        "nameIt": "Quando possibile, stendi invece di usare l'asciugatrice.",
        "descriptionIt": "Se possibile, preferisci sempre stendere i vestiti all'aria, invece che usare l'asciugatrice. Se hai bisogno di usare l'asciugatrice ci sono varie cose che puoi fare per ridurre i consumi:, centrifuga i vestiti al minimo a 1000 giri al minuto, usala a pieno carico, usa il sensore di umidità e tieni pulito il filtro.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Run your dishwasher during off-peak hours.",
        "description": "Run your dishwasher during off-peak hours, e.g. after 10 p.m., when possilbe. Many dishwashers now have timers to enable this.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Run your dishwasher only when it is fully loaded.",
        "description": "Why turn on your dishwasher when it is half empty? You can also use the energy-saving cycles of your dishwasher whenever possible.",
        "nameSe": "Kör endast diskmaskinen när den är full.",
        "descriptionSe": "Kör endast diskmaskinen när den är full för att minska energianvändningen. Använd energisparläge om din maskin har det.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Rinse your dishes with cold water when possible.",
        "description": "If you must rinse your dishes before loading them to the dishwasher, use only cold water so you're not running up your energy bill by heating water unnecessarily.",
        "nameSe": "Skölj inte tallrikar som ska diskas i diskmaskin.",
        "descriptionSe": "Skölj inte tallrikar och annan disk innan du ställer in dem i diskmaskinen, det slösar energi och kan till och med ge ett sämre diskresultat. Skrapa istället av din tallrik innan du ställer den i diskmaskinen om det finns matrester kvar.",
        "nameIt": "Non sciacquare i piatti con acqua calda prima di metterli in lavastoviglie.",
        "descriptionIt": "Se usi la lavastoviglie non sciacquare i piatti in acqua calda, prima di caricarla. É sufficiente dar loro una passata con una spazzola per lavare i piatti o, al limite, sciacquarli con acqua fredda.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Don't keep hot water flowing when you wash your dishes by hand.",
        "description": "Don't keep a steady stream of hot water flowing, when you wash your dishes by hand. According to research, a load of dishes cleaned in a dishwasher requires 37% less water than washing dishes by hand. However, if you fill the wash and rinse basins instead of letting the water run, you'll use half as much water as a dishwasher.",
        "nameSe": "Diska inte under rinnande vatten.",
        "descriptionSe": "Lämna inte varmvattnet rinnande om du diskar för hand, istället kan du fylla vatten i diskhon.",
        "nameIt": "Non lavare i piatti con acqua corrente.",
        "descriptionIt": "Quando lavi i piatti a mano tappa il lavello in cui lavi i piatti e quello in cui li sciacqui. In questo modo consumerai fino al 74% di acqua in meno.",
        "type": "routine",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "If you can, speed up your daily cooking process.",
        "description": "Using stove for 10 minutes consumes around 1/3 kWh electricity. How to speed up your cooking process? You can, e.g., cut things like vegetables into smaller and evenly sized pieces so they can get more quickly cooked. Don't over-fill pots with water when cooking vegetables. Simmer food, never boil furiously. Use the lid on the pot as much as possible.",
        "nameSe": "Hitta vägar till snabbare matlagning.",
        "descriptionSe": "Att använda spis och ugn kortare tid minskar energianvändningen. Du kan t.ex. skära grönsaker i mindre och jämnstora bitar så att de tillagas snabbare, använda lock när du kokar upp vatten och kokar mat, inte använda onödigt mycket vatten i kastrullen och inte stormkoka maten på hög temperatur. Utnyttja eftervärmen på plattan eller i ugnen genom att stäga av spisen strax innan maten är klar.",
        "nameIt": "Riduci i tempi di cottura.",
        "descriptionIt": "Non riempire a dismisura d'acqua la pentola in cui cuoci la pasta, impiegherà molto più tempo a bollire. Considera poi che usando il coperchio impiegherà circa il 30% di tempo in meno a bollire, ovvero il 30% in meno di energia.\nRicorda che tenere alto il fuoco sotto una pentola che sta già bollendo non fa cuocere le cose più in fretta; far sobbollire il cibo è molto più efficiente.",
        "type": "routine",
        "impact": 1,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Use energy efficient cooktops.",
        "description": "On average, about 500 kWh spends on cooking per year. If you want to upgrade your kitchen, consider modern induction cooktops. They heat quicker and are more energy efficient than traditional cooktops. With an induction cooktop, the energy saving when boiling one liter of water is 33% compared with a ceramic glass cooktop.",
        "nameSe": "Använd en energieffektiv spis.",
        "descriptionSe": "Om du ska köpa en ny spis, överväg en induktionshäll. De tillagar maten snabbare och mer energieffektivt jämfört med traditionella spisar.",
        "type": "onetime",
        "impact": 3,
        "effort": 3
    },
    {
        "category": "kitchen",
        "name": "When cooking on top of your range, match the size of the pan to the heating element.",
        "description": "If you use cooking plates, ensure that the pans and pots have flat bottoms and have the right size for the plate you use. If your pan and the cooking plate have matching size, more heat will get to the pan and less will be lost to the surrounding air. Believe it or not, a 15 cm pan on an 20 cm burner will waste more than 40 percent of the energy!",
        "nameSe": "Matcha storleken på spisplattan med kastrullens/pannans storlek.",
        "descriptionSe": "Se till att storleken på plattan och kärlet du ska tillaga maten i matchar i storlek för att inte använda onödigt mycket energi. Om du har en 15 cm kastrull på en 20 cm platta kan mer än 40% av spisens energi gå förlorad.",
        "nameIt": "Non cucinare su fuochi troppo grandi.",
        "descriptionIt": "Se la fiamma “deborda” rispetto al fondo della pentola, quell'energia andrà in grandissima parte sprecata. Ricordati di cucinare sul fuoco della giusta dimensione!",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Boil energy efficient eggs.",
        "description": "Boil the water with the eggs in. Turn off the heat when the water boils and then take the pan off the heat. Set the timer for approximately 9-10 and 4-6 minutes for the hard- and soft-boiled eggs.",
        "nameSe": "Tillaga ägg energieffektivt.",
        "descriptionSe": "Koka upp vattnet med äggen i. Stäng av värmen när vattnet kokar och ta av kastrullen från plattan. Vänta 9-10 minuter för hårdkokta ägg och 4-6 minuter för löskokta.",
        "type": "routine",
        "impact": 1,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Don't keep ventitaling/extractor fans running too long, especially in winter.",
        "description": "Turn off kitchen and/or bath-ventilating fans after they've done their job - these fans can blow out a house-full of heated air if inadvertently left on.",
        "nameSe": "Stäng av köks- och badrumsventilation direkt när den har gjort sitt jobb.",
        "descriptionSe": "Stäng av ventilationen i kök och badrum direkt när det är färdigventilerat. Om ventilationen lämnas på blåses husets uppvärmda luft ut i onödan vilket slösar energi, speciellt på vintern.",
        "nameIt": "Spegni la cappa dei fornelli, quando non ti serve.",
        "descriptionIt": "Considera che, in inverno, la cappa di ventilazione della cucina trasporta fuori dalla tua casa l'aria calda. Per questo è bene ricordarsi di spegnerla quando non serve più.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Use microwave ovens where possible.",
        "description": "Microwave ovens, because of their smaller wattage and faster cooking times, use around 50% and up to 70% less electricity than convectional cooking methods, and they don't heat up your kitchen (particualrly good for summer). Keep your microwave clean to reduce cooking times to a minimum. Consider using them to bake yams, steam your favorite fresh vegetables, or heat up leftovers and gravy for a midnight snack. They're especially efficient for smaller portions or items, but when it comes to large items, your oven or stovetop are usually more efficient.",
        "nameSe": "Värm mat i mikron istället för på spisen eller i ugnen.",
        "descriptionSe": "Mikrovågsugnen använder 50-70% mindre energi än spisen och ugnen, och är speciellt effektiv när det handlar om mindre mängder mat. Se till att mikron är ren för att minska uppvärmningstiden.",
        "nameIt": "Ricordati del microonde.",
        "descriptionIt": "Ricorda che per riscaldare o cuocere piccole quantità di cibo, il microonde è generalmente più efficiente degli altri metodi.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Use a jug or kettle to boil water.",
        "description": "Use a jug or kettle, not the stove, to boil water. Not only will it heat water quickly, it is also 50% more efficient. Only cook the amount of water you need. Don't overfill and boil more water than that is needed.",
        "nameSe": "Koka vatten i vattenkokare istället för på spisen.",
        "descriptionSe": "Koka vatten i vattenkokare istället för på spisen. Det går både snabbare och drar mindre energi. Koka bara upp så mycket vatten som behövs.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Limit the times the oven door is opened.",
        "description": "It can cause up to 15% loss of hot air each time the door is opened. Don't open the oven door to take a peek at what's cooking inside. Instead, turn on the oven light and check the cooking status through the oven window. Opening the oven door lowers the temperature inside which increases cooking time and wastes energy.",
        "nameSe": "Håll ugnsluckan stängd så mycket som möjligt när ugnen är på.",
        "descriptionSe": "Upp till 15% av ugnens värme kan försvinna varje gång du öppnar luckan, så gör det bara när du verkligen behöver. Att öppna luckan sänker temperaturen, vilket både slösar energi och ökar tillagningstiden.",
        "nameIt": "Non aprire lo sportello del forno quando lo stai usando.",
        "descriptionIt": "Aprire lo sportello del forno mentre si sta cucinando fa uscire fino al 15% di aria calda, aumentando i tempi di cottura e il dispendio energetico. Per questo è meglio controllare la cottura guardando attraverso il vetro.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "kitchen",
        "name": "Use your oven efficiently.",
        "description": "As long as your oven is on, cook several items at the same time. Just make sure you leave enough room for the heat to circulate around each casserole and pie plate. Turn the oven off several minutes before you remove the food. If you can, have a baking day, or bake biscuits and cakes before and after using oven for a roast.",
        "nameSe": "Använd ugnen energieffektivt.",
        "descriptionSe": "Passa på att laga flera rätter samtidigt när du väl använder ugnen. Se bara till att det finns plats i ugnen för värmen att cirkulera. Stäng av ugnen strax innan du tar ut maten för att utnyttja eftervärmen.",
        "nameIt": "Usa il forno in maniera efficiente.",
        "descriptionIt": "Compatibilmente con le ricette utilizzate, in forno si possono cuocere più pietanze contemporaneamente, basta accertarsi che l'aria calda riesca a circolare tra le varie pirofile o tra i “piani” di teglie. Ricorda poi che tenendo lo sportello chiuso il caldo si conserva all'interno del forno: in molti casi è quindi possibile spegnerlo una decina di minuti prima che il cibo sia pronto.",
        "type": "routine",
        "impact": 2,
        "effort": 2
    },
    {
        "category": "kitchen",
        "name": "A slow cooker and a toaster stove is handy for a kitchen. ",
        "description": "Slow cookers (crock-pots) are perfect for busy families. On average, they use less energy than stoves. If you're baking or broiling small food items, a toaster oven is ideal because they use one-third the energy of a bigger oven.",
        "nameSe": "Om du gillar långkok, överväg en \"slow cooker\".",
        "descriptionSe": "En \"slow cooker\" eller \"croc pot\" är en köksmaskin som fungerar bra för långkok och som generellt drar mindre energi för tillagning än spis och ugn.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Do not overheat water for daily uses such as cleaning and bathing.",
        "description": "Water heating can account for 14% to 25% of the energy consumed in your home. Turn down the temperature of your water heater to the warm setting (48°C). You'll not only save energy, you'll avoid scalding your hands.",
        "nameIt": "Se hai un boiler, non surriscaldare l'acqua.",
        "descriptionIt": "Il riscaldamento dell'acqua calda sanitaria può pesare tra il 14% e il 25% dei consumi energetici domestici. Se hai un boiler non surriscaldare l'acqua: tenendola attorno ai 48° risparmierai (ed eviterai di scottarti le mani)",
        "type": "onetime",
        "impact": 2,
        "effort": 2
    },
    {
        "category": "heating",
        "name": "Switch off your hot water system when on holidays.",
        "description": "If you are on holidays or going away for a week or more, please turn off your hot water system. This can help you save money and energy.",
        "type": "irregular",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Use hot water efficiently.",
        "description": "There are many things you can do to use hot water more efficiently. For example, don't allow hot water to run down the sink as you wash or shave. Plug the sink. Also, try to avoid using small amounts of hot water if cold water will do. Each time you run the hot tap a litre or more of water that was heated goes cold.",
        "nameSe": "Använd varmvatten energieffektivt.",
        "descriptionSe": "Låt inte varmvattnet rinna när du tvättar eller rakar dig och använd inte varmvatten i de fall kallvatten fungerar lika bra.",
        "nameIt": "Usa l'acqua calda in maniera efficiente.",
        "descriptionIt": "Se puoi, cerca di usare l'acqua fredda quando te ne serve un piccolo quantitativo. Considera che, aprendo il rubinetto dell'acqua calda e chiudendolo subito dopo, almeno un litro d'acqua rimane nei tubi a raffreddarsi.",
        "type": "routine",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Adjust your home temperature.",
        "description": "Set your thermostat to 20 degrees or as low as conformtable during the day and evening. Turn down the heating approximately one hour before you go to bed. Your room will certainly still remain warm for another hour. Do you know that 75% of the total energy costs are for heating? Every degree lower saves 5% heating costs.",
        "nameSe": "Justera värmetermostaten på dina element.",
        "descriptionSe": "Om du kan välja temperatur, sätt termostaten på 20 grader (eller så lågt som känns ok) under dagen och kvällen. Sänk temperaturen ungefär en timme innan du går och lägger dig, rummet kommer fortfarande vara varmt i en timme till. Varje grad kallare i rummet sparar ungefär 5% energi.",
        "nameIt": "Regola la temperatura di casa.",
        "descriptionIt": "Circa il 75% dei costi energetici di una casa sono dovuti a spese di riscaldamento. Considera che per ogni grado riscaldato in meno si risparmia il 5% dei costi di riscaldamento. Per risparmiare, oltre ad abbassare la temperatura in casa, puoi abbassare il termostato fino a qualche ora prima di andare a dormire.",
        "type": "routine",
        "season": "winter",
        "impact": 5,
        "effort": 2
    },
    {
        "category": "heating",
        "name": "Use electrical floor heating sparingly.",
        "description": "Costs can easily run away under your feet.",
        "nameSe": "Använd golvvärme sparsamt.",
        "descriptionSe": "Golvvärme drar mycket energi vilket ofta kan ses på elräkningen.",
        "type": "routine",
        "season": "winter",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Do you have a programmable thermostat?",
        "description": "You can adjust heating tempaerture manually, but a programmable thermostat never forgets to turn down the heat at night and it can raise the temperature before you get out of bed in the morning.",
        "nameSe": "Har du ett programmerbart termostat?",
        "descriptionSe": "Du kan justera temperaturen manuellt, men om du har möjlighet att programmera termostaten kan du välja att temperaturen automatiskt ska sänkas t.ex. på natten och sedan höjas igen innan du går upp på morgonen.",
        "nameIt": "Hai un termostato programmabile?",
        "descriptionIt": "Se hai un termostato programmabile, usalo. Lui certamente non si dimenticherà di abbassare la temperatura la notte, inoltre la potrà alzare poco prima del tuo risveglio e del tuo rientro dal lavoro.",
        "type": "onetime",
        "season": "winter",
        "impact": 4,
        "effort": 3
    },
    {
        "category": "heating",
        "name": "Maintain your heating systems.",
        "description": "Schedule service for your heating system. Find out what maintenance is required to keep your heating system operating efficiently.",
        "nameIt": "Programma la manutenzione degli impianti di riscaldamento.",
        "descriptionIt": "Programma la manutenzione degli impianti di riscaldamento in modo che possano lavorare al massimo dell'efficienza possibile",
        "type": "regular",
        "season": "winter",
        "impact": 4,
        "effort": 3
    },
    {
        "category": "heating",
        "name": "Clean your wood- and pellet-burning heaters.",
        "description": "Clean the flue vent regularly and clean the inside of the appliance with a wire brush periodically to ensure that your home is heated efficiently.",
        "nameIt": "Effettua la pulizia delle canne fumarie di stufe a legna e a pellet.",
        "descriptionIt": "Pulire regolarmente le canne fumarie migliorerà il funzionamento della stufa (oltre a scongiurare il rischio di incendi)",
        "type": "regular",
        "season": "winter",
        "impact": 4,
        "effort": 3
    },
    {
        "category": "heating",
        "name": "Install quilted curtains.",
        "description": "If you're turning up the heat in the house to compensate for drafty windows, consider quilted curtains, which can increase your comfort and let you keep the temp down.",
        "nameSe": "Sätt upp tjocka gardiner om det är dragigt.",
        "descriptionSe": "Om du ökar inomhustemperaturen för att det drar från fönstren kan du istället prova att sätta upp tjocka gardiner för att hålla kylan borta.",
        "nameIt": "Se gli infissi fanno passare molti spifferi, metti delle tende pesanti.",
        "descriptionIt": "Se a causa degli spifferi devi alzare il riscaldamento o aumentare i carichi di legna nella stufa, considera la possibilità di mettere alle finestre tende molto pesanti, la sera.",
        "type": "onetime",
        "season": "winter",
        "impact": 3,
        "effort": 2
    },
    {
        "category": "heating",
        "name": "Air quickly and intelligently.",
        "description": "A short cross-draft is more effective than leaving a window open. Just make sure that the radiators by the windows are shut off for half an hour after airing.",
        "nameSe": "Vädra snabbt och med tvärdrag.",
        "descriptionSe": "Det är bättre att vädra en kort stund med tvärdrag än att lämna fönstret öppet länge. Tänk på att stänga av eventuella element under fönstret under vädringen och en halvtimme efter.",
        "nameIt": "Arieggia le stanze in modo veloce ed efficiente.",
        "descriptionIt": "Arieggiare aprendo tutte le finestre per poco tempo è molto più efficiente che aprire solo una finestra per più tempo o, peggio, tenere costantemente aperte le finestre a ribalta. Considera che se ottieni una bella corrente d'aria la casa sarà perfettamente arieggiata in meno di 5 minuti, in caso contrario potrebbe essere necessario fino a un quarto d'ora. Se possibile, spegni il riscaldamento mentre stai arieggiando. Se puoi, arieggia casa nelle ore in cui l'aria esterna è più calda.",
        "type": "routine",
        "season": "winter",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Enjoy and use sunlight.",
        "description": "Open curtains on your south-facing windows during the day to allow sunlight to naturally heat your home, and close them in the evening and at night to reduce the chill you may feel from cold windows.",
        "nameSe": "Utnyttja solen när det är kallt.",
        "descriptionSe": "Öppna gardiner och persienner på fönster mot söder för att låta solljuset värma rummet under dagtid, den del av året som uppvärmning krävs, och stäng dem på natten för att hålla kylan ute.",
        "nameIt": "Sfutta la luce del sole.",
        "descriptionIt": "Nelle ore centrali sfrutta il calore del sole per riscaldare casa: apri completamente le tapparelle/persiane e scosta le tende.",
        "type": "routine",
        "season": "winter",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Arrange your rooms so that you don't sit in cold.",
        "description": "If necessary and possible, move your furniture around so you are sitting near interior walls - exterior walls and older windows are likely to be drafty. Don't sit in the draft.",
        "nameSe": "Möblera så att du inte sitter där det är kallt.",
        "descriptionSe": "Om möjligt, flytta möbler där du sitter ner så att de står mot innerväggar istället för ytterväggar, det är ofta mer dragigt vid ytterväggarna.",
        "nameIt": "Organizza la stanza in modo di non sedere al freddo.",
        "descriptionIt": "Ricorda che le zone adiacenti alle pareti esterne sono spesso più fredde. In tal caso, puoi sistemare lungo i muri esterni mobili come librerie e credenze e tenere tavoli e divani in posizione centrale o lungo i muri interni.",
        "type": "onetime",
        "season": "winter",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "If you have blinds or drapes on windows, use them.",
        "description": "Keep them open with direct sun exposure (usually on the south side of the house) to let the sunlight heat the room. Heating doesn't get any cheaper than this! At night, close the blinds or drapes to cover the cold glass.",
        "type": "onetime",
        "season": "winter",
        "impact": 2,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "A way to find air leaks.",
        "description": "Locating air leaks can be tricky. They're often so small as to be hardly noticeable. To find them, follow a trail of smoke. Close all the windows in the house, turn off all the fans and exhaust fans, and shut off the furnace. Light some incense and walk slowly around the outer walls of the house. Anywhere you notice the smoke blowing away from something or being sucked toward something, there's probably an air leak. Now that you've found it, seal it!",
        "nameSe": "Se till att fönster och dörrar inte är dragiga.",
        "descriptionSe": "Om det drar från fönster eller dörrar kan du kontrollera om tätningslisterna behöver bytas. Ser de gamla tätningslisterna dåliga ut är det lätt att ersätta med nya.",
        "nameIt": "Tova e sigilla gli spifferi.",
        "descriptionIt": "Individuare gli spifferi non è semplice perchè spesso sono tanto deboli che a malapena li percepiamo. Puoi verificare chiudendo porte/finestre e accendendo un incenso. Posiziona l'incenso vicino a ai punti dove è più facile che ci siano spifferi (porte, finestre, camini, tubature che escono dal muro e prese elettriche). Osserva come si comporta il fumo: se viene “soffiato via” o risucchiato verso qualcosa, è facile che ci sia una perdita da sigillare: ora che lo sai puoi provvedere! \nSe in casa avete i fornelli a induzione, informatevi riguardo alla possibilità di chiudere i fori di ventilazione che per legge sono obbligatori nelle cucine con fuochi a metano/gpl.",
        "type": "onetime",
        "season": "winter",
        "impact": 3,
        "effort": 3
    },
    {
        "category": "heating",
        "name": "Keep fireplaces shut.",
        "description": "Traditional fireplaces are an energy loser - it's best not to use them because they pull heated air out of the house and up the chimney. When not in use, make sure the damper is closed. Keeping the damper open is like keeping a window wide open during the winter. Before closing the damper, make sure that you don't have any smoldering embers. If you decide not to use a fireplace, then block off the chimney with a piece of rigid insulation from the hardware store that fits snugly into the space (dampers don't shut fully without some leaking).",
        "nameIt": "Tieni chiusa la canna fumaria dei caminetti tradizionali.",
        "descriptionIt": "Se avete caminetti tradizionali in casa, accertatevi sempre che la canna fumaria sia chiusa, quando non li usate. La canna fumaria può essere chiusa tramite l'apposita valvola di tiraggio, ma considerate che un pezzo di isolante rigido tagliato su misura è più efficace.",
        "type": "onetime",
        "season": "winter",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "heating",
        "name": "Stop fireplace heat loss, use airtight fireplace doors.",
        "description": "Wood-burning fireplaces can warm up a room, but more often, they rob a house of heat by letting it escape up the chimney. If you have a modern fireplace with a cold air intake from outside, make sure you equip it with an airtight door. If you have an older fireplace that uses room air for combustion, equip it with a door that has operable vents. And only keep those vents open when you have a fire in the fireplace. Otherwise, heat will constantly be sucked out of the house.",
        "nameIt": "Impedisci al caldo di scappare su per il camino.",
        "descriptionIt": "I caminetti tradizionali non sono un sistema di riscaldamento efficiente perchè lasciano scappare buona parte del calore dalla canna fumaria. Se in casa hai un caminetto moderno, con una presa d'aria fredda dall'esterno, assicurati di dotarlo di una porta ermetica. Se invece usi spesso un caminetto tradizionale, che utilizza l'aria della stanza per la combustione lo puoi dotare di una porta con delle prese d'aria regolabili. In tal modo potrai chiuderle facilmente quando il camino è in uso, e il caldo non verrà risucchiato fuori.",
        "type": "onetime",
        "season": "winter",
        "impact": 3,
        "effort": 1
    },
    {
        "category": "bathroom",
        "name": "If possible, shower rather than bath, as a short shower will use less hot water. Shower quickly.",
        "description": "Shorten showers: simply reducing that lingering time by a few minutes can save hundreds of gallons of hot water per month for a family of four. Showers account for 2/3 of your water heating costs. Cutting your showers in half will reduce your water heating costs by 33%. If you shower five minutes instead of 15, you reduce annual consumption by 500 kWh.",
        "nameSe": "Duscha istället för att bada eller spendera kortare tid i duschen.",
        "descriptionSe": "Det krävs midre vatten för att duscha än att bada. Att korta duschtiden kan också spara mycket vatten i det långa loppet.",
        "nameIt": "Preferisci una doccia veloce a un bagno.",
        "descriptionIt": "Scaldare l'acqua per la doccia incide circa sui 2/3 dei costi di riscaldamento dell'acqua. Dimezzando il tempo passato sotto la doccia, una famiglia di quattro persone può risparmiare centinaia di litri d'acqua calda e ridurre i costi di riscaldamento dell'acqua di circa il 33%. \nSe proprio vuoi rilassarti sotto l'acqua, considera quanta acqua eroga la tua tua doccia al minuto: potrebbe addirittura convenirti fare un bel bagno. Un modo pratico per capirlo è tappare la vasca mentre stai facendo una doccia in tutto relax, e vedere fino a che livello arriva l'acqua.",
        "type": "routine",
        "impact": 5,
        "effort": 2
    },
    {
        "category": "bathroom",
        "name": "Change old faucets and shower heads. Install low-flow showerheads.",
        "description": "Separate cold and hot water taps consume energy unnecessarily. Modern water-saving faucets run 12 liters per minute, instead of 35. Install thermostat blenders in the shower. Low-flow showerheads and faucets can drastically cut your hot water expenses. Savings of 10-16% of water heating costs.",
        "nameSe": "Installera snålspolande kranar och duschmunstycken.",
        "descriptionSe": "Snålspolande kranar och duschmunstycken kan minska vattenförbrukning med 10-16%.",
        "nameIt": "Consuma meno acqua con manutenzione e riduttori di flusso.",
        "descriptionIt": "Il tuo rubinetto eroga troppa acqua? Per saperlo basta riempire un secchio per un minuto esatto e poi misurare il contenuto. Ricorda che i depositi di calcare rendono qualsiasi tipo di rubinetto meno efficiente: smonta ghiera/aereatore del rubinetto, mettilo a bagno in aceto per una notte ed effettua nuovamente il test. Se i tuoi rubinetti consumano ancora troppo, considera che i riduttori di flusso più efficienti consentono di scendere sotto i 4 litri al minuto e che il loro prezzo è contenuto. Ricorda che ridurre il consumo d'acqua è doppiamente importante perchè ti permette di risparmiare anche sull'energia che usi per scaldarla!",
        "type": "onetime",
        "impact": 5,
        "effort": 3
    },
    {
        "category": "bathroom",
        "name": "Renew seals and washers on dripping taps.",
        "description": "A hot water tap dripping once a second for a day can waste enough hot water for an extra person.",
        "nameSe": "Fixa droppande kranar.",
        "descriptionSe": "En kran som står och droppar en hel dag (en droppe per sekund) kan göra av med lika mycket vatten som en person använder under en dag.",
        "nameIt": "Se i rubinetti perdono, sostituisci guarnizioni e ...",
        "descriptionIt": "un rubinetto che gocciola una volta al secondo consuma come se in casa ci fosse una persona in più. Se hai rubinetti che gocciolano, cambia le guarnizioni!",
        "type": "irregular",
        "impact": 2,
        "effort": 2
    },
    {
        "category": "bathroom",
        "name": "Measure and limit your water consumption during shower with this trick.",
        "description": "First put a big container under the fully-opened shower for a minute and measure the amount of water that came out. Impressed? Mark an acceptable, still comfortable position of the water regulator, e.g., with some duct tape, to know exactly how much to open the tap every time. You can reduce your water consumption by 50% -- and also energy used for heating!",
        "nameSe": "Mät och minska din vattenanvändning i duschen.",
        "descriptionSe": "Testa hur mycket vatten som kommer ut ur duschmunstycket när kranen är helt öppen genom att ha en stor hink i duschen och spola i en minut. Testa sedan hur mycket du kan stänga kranen och samtidigt behålla ett okej tryck i duschmunstycket. Se hur mycket vatten du kan spara genom att jämföra hur mycket vatten som samlas i hinken under en minut vid det lägre trycket.",
        "type": "routine",
        "impact": 3,
        "effort": 2
    }
];
